### ISSUE TITLE
Game Crash on ESP 

### ISSUE THREAD

**Issue by PrimeTDMomega** [pastimee/shoreline#16] opened 2024-03-30 05:45 UTC
ESP is fine but game crashes without the crash report when it tries to render End Crystals.

**Comment by master7720** [comment] 2024-03-30 05:49
weird esp works fine both modes

**Comment by PrimeTDMomega** [comment] 2024-03-30 06:11
Not crystals that crash it but something crashes it

**Comment by master7720** [comment] 2024-03-30 06:30
what launcher do you use? cause most launchers have real time reports like prismMC. if yours have that feature you could just copy and paste the whole log when it crashes.

**Comment by master7720** [comment] 2024-03-30 06:31
![image](https://github.com/pastimee/shoreline/assets/80098736/78392d35-a606-483f-9517-4da25778c216)

sorry am tired am talking abt this you could just copy and paste the whole thing when it crashes

**Comment by PrimeTDMomega** [comment] 2024-03-30 06:33
I use official launcher rofl

**Comment by master7720** [comment] 2024-03-30 06:38
that could work go into settings and find the setting "Enable Developer" how when you go back into the main launcher screen there should be a button called "Console" or "Developer Console"and boom

**Comment by PrimeTDMomega** [comment] 2024-03-30 06:53
```
Unreported exception thrown!
java.lang.IllegalStateException: Already building!
	at net.minecraft.class_287.method_1328(class_287.java:109)
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:50)
	at net.minecraft.class_918.method_29711(class_918.java:218)
	at net.minecraft.class_918.method_23179(class_918.java:158)
	at net.minecraft.class_918.method_23177(class_918.java:271)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_759.method_3228(class_759.java:620)
	at net.minecraft.class_759.method_22976(class_759.java:396)
	at net.minecraft.class_757.method_3172(class_757.java:798)
	at net.minecraft.class_757.method_3188(class_757.java:1125)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
12:22:33.462
Shoreline
Shoreline-ShutdownHook
[Shoreline] Saving configurations and shutting down!
12:22:34.061
launcher
main

12:22:34.061
monitor
Process Monitor
Process crashed with exit code -1
```

**Comment by master7720** [comment] 2024-03-30 07:04
synchronizing issue?..... maybe?

**Comment by pastimee** [comment] 2024-03-30 14:51
The issue is when rendering items the buffer state is leaked because esp is already using the buffer to draw. You can test this by holding any item, this will cause esp to crash. We are working on a fix for this

**Comment by pastimee** [comment] 2024-04-01 16:42
57e2628

**Closed by pastimee** 2024-04-01 16:42 UTC
